apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: radius-app
  namespace: radius-app
spec:
  interval: 1m
  url: https://github.com/willdavsmith/radius-flux-app
  ref:
    branch: main
