---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: radius-system
spec:
  interval: 5m0s
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: contour
  namespace: radius-system
spec:
  interval: 30m
  chart:
    spec:
      chart: contour
      version: "11.1.1"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: radius-system
      interval: 12h
---
