---
apiVersion: v1
kind: Namespace
metadata:
  name: radius-system
  labels:
    toolkit.fluxcd.io/tenant: sre-team
---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: radius
  namespace: radius-system
spec:
  interval: 24h
  url: oci://ghcr.io/radius-project/helm-chart
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: radius
  namespace: radius-helm
spec:
  interval: 30m
  chart:
    spec:
      chart: radius
      version: "0.36.0"
      sourceRef:
        kind: HelmRepository
        name: radius
        namespace: radius-system
      interval: 12h
