kind: DeploymentTemplate
apiVersion: radapp.io/v1alpha3
metadata:
  name: radius-app.bicep
  namespace: radius-system
spec:
  parameters: |
    {
      "namespace": {
        "value": "radius-app"
      },
      "replicas": {
        "value": 3
      }
    }
