apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius-flux-controller
  namespace: radius-system
  labels:
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: radius-flux-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: radius-flux-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: radius-flux-controller
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: ghcr.io/willdavsmith/radius-flux-controller:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: http-prom
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --log-level=info
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}

