apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radius-flux-controller
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories/status
  verbs:
  - get
- apiGroups:
  - radapp.io
  resources:
  - applicationdeployments
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radius-flux-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radius-flux-controller
subjects:
- kind: ServiceAccount
  name: radius-flux-controller
  namespace: radius-system
