---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radius-flux-controller
  namespace: radius-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radius-flux-controller
rules:
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - source.toolkit.fluxcd.io
  resources:
  - gitrepositories/status
  verbs:
  - get
- apiGroups:
  - radapp.io
  resources:
  - applicationdeployments
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radius-flux-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radius-flux-controller
subjects:
- kind: ServiceAccount
  name: radius-flux-controller
  namespace: radius-system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radius-flux-controller
  namespace: radius-system
  labels:
    
    control-plane: controller
spec:
  selector:
    matchLabels:
      app: radius-flux-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: radius-flux-controller
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
    spec:
      serviceAccountName: radius-flux-controller
      terminationGracePeriodSeconds: 10
      containers:
        - name: manager
          image: ghcr.io/willdavsmith/radius-flux-controller:latest
          imagePullPolicy: Always
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
          ports:
            - containerPort: 8080
              name: http-prom
          env:
            - name: RUNTIME_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - --log-level=info
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 50m
              memory: 64Mi
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
---